### ISSUE TITLE
Unexpected error: Object.entries is not a function

### ISSUE THREAD

**Issue by antifob** [joona/aws-es-proxy#6]
Version 1.0.3 is causing problem here:

```
Unexpected error: Object.entries is not a function
TypeError: Object.entries is not a function
    at /usr/lib/node_modules/aws-es-proxy/index.js:42:26
    at send.handleRequest (/usr/lib/node_modules/aws-es-proxy/index.js:20:10)
    at /usr/lib/node_modules/aws-es-proxy/index.js:97:22
    at next (native)
    at onFulfilled (/usr/lib/node_modules/aws-es-proxy/node_modules/co/index.js:65:19)
    at /usr/lib/node_modules/aws-es-proxy/node_modules/co/index.js:54:5
    at co (/usr/lib/node_modules/aws-es-proxy/node_modules/co/index.js:50:10)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/aws-es-proxy/index.js:96:5)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
```

Pinning to 1.0.2 solves the issue. Using node 5.12.0.

**Comment by joona** [comment]
Thanks for reporting the bug. I've refactored the code to remove Object.entries usage, which is not available on node v5. Fixed in 1.0.4
